name: tour_planner1
description: A tourism app for Sri Lanka

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  google_fonts: 6.3.0
  http: 1.5.0
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
